version: '3.9'

services:
  roboracer_sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roboracer_sim_dev
    network_mode: host   # use host networking
    ipc: host
    privileged: true

    tty: true
    stdin_open: true

    environment:
      - DISPLAY=${DISPLAY}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

